In [20]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [22]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [23]:
#setting 

#setting 

columns = [
            'CD','total_rats', 'tons_of_refuge','tons_of_MGP', 'tons_of_paper', 'tons_res_organics', 'tons_sch_organics', 'tons_leaves_organics',
             'tons_xmastrees', 'pct_LU1', 'pct_LU2', 'pct_LU3', 'pct_LU4', 'pct_LU5', 'pct_LU6', 'pct_LU7',
             'pct_LU8', 'pct_LU9', 'pct_LU10', 'pct_LU11', 'percentile'
]

target = ["percentile"]

In [24]:
# Load the data
# "mock-data" file generated from xls spreadsheets of actual data to be used after SQL db developement


df = pd.read_csv('rats_Garb_LU.csv')
df.head()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
df.tail(20)

# Fill the null rows with zeros assuming particularly 
#garbage collection of organics etc is not performed and is included in refuge
df.fillna(value=0, axis=1)
df.tail(20)
df.count()

CD                      59
total_rats              59
tons_of_refuge          59
tons_of_MGP             59
tons_of_paper           59
tons_res_organics       59
tons_sch_organics       59
tons_leaves_organics    59
tons_xmastrees          59
pct_LU1                 59
pct_LU2                 59
pct_LU3                 59
pct_LU4                 59
pct_LU5                 59
pct_LU6                 59
pct_LU7                 59
pct_LU8                 59
pct_LU9                 59
pct_LU10                59
pct_LU11                59
dtype: int64

In [25]:
# Convert the target column values to Below and Above based on rat data 50%tile values

x = {'Below': 'Below 50%'}   
df = df.replace(x)

x = dict.fromkeys(['Above'], 'Above 50%')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

#df.head()
df.tail(20)

,CD,total_rats,tons_of_refuge,tons_of_MGP,tons_of_paper,tons_res_organics,tons_sch_organics,tons_leaves_organics,tons_xmastrees,pct_LU1,pct_LU2,pct_LU3,pct_LU4,pct_LU5,pct_LU6,pct_LU7,pct_LU8,pct_LU9,pct_LU10,pct_LU11
39,10 MANHATTAN,6831,1131518.8,54826.4,53265.6,102.9,1005.6,54.9,501.3,4.1,19.8,22.3,23.2,4.9,0.8,0.9,14.3,6.1,0.6,3.0
40,11 MANHATTAN,3286,1006505.2,44949.0,47872.4,3.8,778.3,10.8,360.9,0.3,4.4,17.5,7.1,1.9,0.4,10.0,9.5,43.1,1.5,4.3
41,12 MANHATTAN,4920,2139581.2,147001.7,112987.8,824.9,2409.6,0.0,833.4,0.4,8.4,10.6,9.8,2.5,0.4,7.7,8.0,43.7,1.8,6.9
42,01 QUEENS,3032,1744235.6,163543.1,218689.2,0.0,0.0,1454.6,894.7,16.4,17.5,7.4,6.0,6.8,8.7,20.1,4.0,7.4,2.3,3.4
43,02 QUEENS,2348,1060287.7,98901.4,134628.3,2327.0,1677.4,720.2,596.6,11.4,8.4,4.5,4.1,6.1,23.6,12.8,3.9,15.4,5.8,4.0
44,03 QUEENS,1752,1808392.6,133626.9,138515.3,0.0,0.0,1258.6,618.5,42.6,18.3,9.3,5.2,9.8,0.5,1.1,6.5,3.9,1.9,0.9
45,04 QUEENS,1641,1590480.8,111604.2,125139.7,0.0,0.0,668.7,393.4,27.3,28.3,11.0,8.1,6.6,1.9,5.3,6.8,2.1,1.3,1.3
46,05 QUEENS,4083,1857490.3,198092.1,261565.0,10608.9,4934.7,2867.6,1319.9,31.0,9.8,0.5,3.0,3.0,9.1,6.8,2.4,31.9,1.3,1.1
47,06 QUEENS,970,1094103.8,98775.5,168834.0,0.0,243.5,3569.3,491.0,41.8,4.4,16.3,5.9,5.9,0.1,6.0,5.5,12.1,0.6,1.2
48,07 QUEENS,1752,2461125.3,203281.2,328594.4,6053.2,0.0,8761.8,1569.2,33.4,6.1,4.2,2.6,4.1,4.0,3.0,5.4,10.7,1.8,24.7
49,08 QUEENS,1134,1405019.7,108542.8,182160.3,3146.7,0.0,6992.7,499.1,42.6,14.9,7.3,1.4,3.0,0.0,0.4,10.8,18.5,0.3,0.8
50,09 QUEENS,1271,1547162.9,143182.3,164202.6,5972.1,2133.1,3060.4,679.4,57.5,10.7,3.5,4.9,4.3,2.7,7.6,4.7,2.1,1.1,0.9
51,10 QUEENS,1602,1516774.5,137171.5,153612.8,6029.1,0.0,3048.8,889.0,52.7,4.8,1.1,1.7,2.9,0.6,5.1,2.5,23.3,0.7,4.6
52,11 QUEENS,522,1229648.9,118238.3,212278.6,7290.6,1038.7,9916.1,1265.4,54.0,10.3,1.6,0.9,2.9,0.2,1.3,5.0,20.5,0.4,2.9
53,12 QUEENS,3572,2674157.6,214459.7,178878.8,0.0,0.0,7919.1,468.8,59.9,3.0,4.7,2.2,3.8,3.5,6.0,7.1,6.1,1.6,2.0
54,13 QUEENS,1356,2226675.4,213201.1,221724.2,7145.0,0.0,10278.2,982.2,32.3,2.8,1.0,0.4,1.4,1.1,48.8,4.3,6.4,0.5,1.0
55,14 QUEENS,743,1109049.8,68770.4,87572.4,2371.2,0.0,912.6,660.8,31.8,3.2,6.9,1.0,1.5,0.6,2.9,4.2,29.1,0.7,18.2
56,01 STATEN ISLAND,3540,2078852.9,184957.2,183049.6,10618.1,0.0,15953.7,1801.6,42.2,4.1,2.2,1.5,5.2,3.5,8.9,7.2,14.7,1.0,9.6
57,02 STATEN ISLAND,1730,1720679.5,151821.3,169045.6,1.8,2904.5,13137.4,1382.6,27.4,2.2,0.7,0.5,4.6,2.9,9.6,10.8,23.5,0.8,17.1
58,03 STATEN ISLAND,2258,2259263.4,204783.0,238894.2,0.0,1691.5,19312.1,2250.0,39.8,1.2,0.2,0.5,3.4,3.2,5.8,4.9,18.6,0.8,21.8

# Split the Data into Training and Testing

In [26]:
# Create our features
# create and drop 'fiftieth2517' column then assign to X
X = df.drop(['CD','total_rats', 'percentile'], axis=1)

# Create our target
y = df['percentile']

X.head()

KeyError: "['percentile'] not found in axis"

In [15]:
X.describe()

NameError: name 'X' is not defined

In [16]:
# Check the balance of our target values
y.value_counts()

NameError: name 'y' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [ ]:
# Check balances
print(Counter(y_train))
print(Counter(y_test))

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [ ]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
# Instantiate
brfc = BalancedRandomForestClassifier(n_estimators=100, random_state=1)

# Fit
brfc.fit(X_train, y_train)

In [ ]:
# Calculated the balanced accuracy score
y_pred = brfc.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

In [ ]:
# Display the confusion matrix
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual Above 50%", "Actual Below 50%"], columns=["Predicted Above 50%", "Predicted Below 50%"])
cm_df

In [ ]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

In [ ]:
# List the features sorted in descending order by feature importance
features_rank = sorted(zip(brfc.feature_importances_, X.columns), reverse=True)
for feature in features_rank:
    print(f"{feature[1]}: ({feature[0]})")

### Easy Ensemble AdaBoost Classifier

In [ ]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
# Instantiate
eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)

# Fit
eec.fit(X_train, y_train)

In [ ]:
# Calculated the balanced accuracy score
y_pred = eec.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

In [ ]:
# Display the confusion matrix
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual Above 50%", "Actual Below 50%"], columns=["Predicted Above 50%", "Predicted Below 50%"])
cm_df

In [ ]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))